In [1]:
import numpy as np

In [38]:
test = np.array([1, 1 + 1e-16])
unique, counts = np.unique(test, return_counts=True)
assert((counts == 2).all())
unique, counts

(array([1.]), array([2]))

In [103]:
test = np.array([1, 1, 1 + 1e-15, 1])
unique, counts = np.unique(test, return_counts=True)
unique, counts

(array([1., 1.]), array([3, 1]))

In [39]:
n = 100
test = np.ones(n)
test[int(n/2):] = 1 + 1e-16
unique, counts = np.unique(test, return_counts=True)
assert((counts == n).all())
unique, counts

(array([1.]), array([100]))

In [40]:
test = np.array([1, 1 + 1e-15])
unique, counts = np.unique(test, return_counts=True)
assert((counts == 1).all())
unique, counts

(array([1., 1.]), array([1, 1]))

In [41]:
n = 100
test = np.ones(n)
test[int(n/2):] = 1 + 1e-15
unique, counts = np.unique(test, return_counts=True)
assert((counts == int(n/2)).all())
unique, counts

(array([1., 1.]), array([50, 50]))

In [42]:
n = 1
test = np.arange(0, n, 1e-6)
unique, counts = np.unique(test, return_counts=True)
assert(counts.shape[0] == test.shape[0])
unique, counts

(array([0.00000e+00, 1.00000e-06, 2.00000e-06, ..., 9.99997e-01,
        9.99998e-01, 9.99999e-01], shape=(1000000,)),
 array([1, 1, 1, ..., 1, 1, 1], shape=(1000000,)))

In [57]:
n = 100
test = -1*np.ones(n)
test[int(n/2):] = -1 - 1e-15
unique, counts = np.unique(test, return_counts=True)
assert((counts == int(n/2)).all())
unique, counts

(array([-1., -1.]), array([50, 50]))

In [58]:
n = 100
test = -1*np.ones(n)
test[int(n/2):] = -1 + 1e-15
unique, counts = np.unique(test, return_counts=True)
assert((counts == int(n/2)).all())
unique, counts

(array([-1., -1.]), array([50, 50]))

In [55]:
n = 100
test = -1*np.ones(n)
test[int(n/2):] = -1 - 1e-16
unique, counts = np.unique(test, return_counts=True)
assert((counts == n).all())
unique, counts

(array([-1.]), array([100]))

In [53]:
n = 100
test = -1*np.ones(n)
test[int(n/2):] = -1 + 1e-16
unique, counts = np.unique(test, return_counts=True)
assert((counts == int(n/2)).all())
unique, counts

(array([-1., -1.]), array([50, 50]))

In [121]:
aux = np.array([1, 1, 1 + 1e-15, 1 + 1e-14])
aux.sort()
aux

array([1., 1., 1., 1.])

In [122]:
mask = np.empty(aux.shape, dtype=np.bool)
mask[:1] = True
mask

array([ True,  True,  True,  True])

In [123]:
aux_firstnan = np.searchsorted(aux, aux[-1], side='left')
aux_firstnan

np.int64(3)

In [124]:
mask[aux_firstnan] = True
mask[aux_firstnan + 1:] = False
mask

array([ True,  True,  True,  True])

In [125]:
mask[1:] = aux[1:] != aux[:-1]
mask

array([ True, False,  True,  True])

In [126]:
ret = (aux[mask],)
ret

(array([1., 1., 1.]),)

In [127]:
np.nonzero(mask) + ([mask.size],)

(array([0, 2, 3]), [4])

In [128]:
np.concatenate(np.nonzero(mask) + ([mask.size],))

array([0, 2, 3, 4])

In [129]:
idx = np.concatenate(np.nonzero(mask) + ([mask.size],))
ret += (np.diff(idx),)
ret

(array([1., 1., 1.]), array([2, 1, 1]))